### ISSUE TITLE
JWT Format

### ISSUE THREAD

**Issue by Elehiggle** [Rob4t/impftermin-telegram#1]
Erst einmal: Krasses Script. Hatte selbst versucht mir einen Bot zu basteln und bin nach einiger Zeit über die Github Suche auf dein Projekt gestoßen.

Ich glaube ich habe mometan alles soweit, Config + pass richtig eingestellt etc., das war auf jeden Fall nicht so einfach für jemanden, der solche Tools nie nutzt :D

Jetzt scheitert es nur noch an dem JWT soweit ich das ausmachen kann:

"illegal base64 data at input byte XXX"

Momentan kriegt man folgenden folgende JWT vom Portal:

`{   "jwttoken" : "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwdWJsaWNVc2VyIiwiTE9DQUxFIjoiZGVfREUiLCJDTElFTlRfSUQiOiIyMjg2OSIsImNyZWF0ZWQiOjE2MjM3MjIzMzM0NzEsImV4cCI6MTYyMzcyMjYzM30.1VFLHlHMoVlDAgUTU75FhSkdBn_Jx_hMeLNTj-d6URQ",   "status" : "OK"}`

Versucht man den Token mit dem Skript zu verwenden, kommt o.g. Fehler. Um das zu beheben musste ich den Teil vor dem letzten Punkt des Tokens abschneiden (dieser Teil ist auf jeden Fall kein json), alle Punkte entfernen und ein Gleichheitszeichen hinten anfügen, sonst möchte das Skript den Token nicht schlucken. Dann kommt aber 401 Unauthorized, weil das Impfportal den Token nicht mehr so akzeptiert. Haben die das Tokenformat vor Kurzem geändert oder mach ich da noch was falsch?

Vielen Dank im Voraus!

**Comment by Rob4t** [comment]
Moin,

Der Token muss **nochmal** Base64 enkodiert werden. Also so wie er aus dem Portal kommt nochmal in Base64 werfen.

Wenn du Lust hast kannst du gerne einen Merge Request da lassen mit einem Vorschlag zur besseren Formulierung in der Readme. Zugegebenermaßen besteht da noch einiges an Optimierungspotential aber für mich und viele andere hat das Tool zu Terminen geführt und deshalb wollte ich es einfach schonmal teilen.

**Comment by Elehiggle** [comment]
Danke, jopp, das war der Fehler :)

Hab mittlerweile ein PR gemacht mit ein paar Erläuterungen.

Leider scheint der Bot aber Broken zu sein. Momentan ist die Situation ja so, dass jeder Termin innerhalb von maximal 10 Sekunden weg ist. Daher habe ich die Sleeps entfernt und lasse den Bot alle 0.3 Sekunden laufen (werde mit meiner IP nicht gebannt, nebenbei läuft noch ein anderer Notification Bot von mir).

Mehrere Termine hat er nicht bekommen, und gerade kam eine sehr große Lieferung i.H.v. 100 Biontech Impfungen rein. Der Bot hat mich zugespammt und keinen einzelnen bekommen. "Error getting free appointments!". Wird wohl irgendwo eine kleine Änderung gegeben haben.

**Comment by Rob4t** [comment]
Den "Error getting free appointments!" habe ich immer nur gekriegt wenn mein Token ungültig war. Es kann aber auch durchaus sein, dass man den auch kriegt wenn man zu langsam ist.

Ich habe heute alleine 2 Termine buchen können also kann ich zumindest nicht bestätigen dass es da Probleme gibt. Aber gerne Issues anlegen / PR stellen.

Das Skript ist auch bewusst nicht darauf ausgelegt alle 0,3 Sekunden zu laufen und ein mal die Minute reicht imho wunderbar aus um an seine Termine zu kommen. Ich werde hier auch nichts anderes Supporten, weil ich es nicht gut finde die API unnötig zu spammen.

**Comment by Elehiggle** [comment]
Es ist möglich, dass man ggf. mit medizinischer oder beruflicher Indikation an andere Termine kommt. Aber ohne alles sind die Termine heute alle innerhalb von einer Sekunde weg. Bevor ich die Modifikation gemacht habe, hat er mich die ganze Nacht bis 10 Uhr morgens nicht einmal im Telegram benachrichtigt, obwohl bereits 40 Termine verfügbar waren. Nach der Änderung auf 0.3 Sekunden benachrichtigt er mich andauernd.

**Comment by Rob4t** [comment]
Hannover ist wenn man geduldig ist eigentlich auch nie ein Problem bei mir gewesen. Habe heute alleine definitiv Termine buchen können. Das Script ist wie gesagt nicht darauf ausgelegt so frequent zu laufen und wird hier in dem Repo auch nicht so umgebaut.

**Comment by Elehiggle** [comment]
Der JWT ist auf jeden Fall valide, hab ich mehrmals nachgeprüft. Hab nun die ganze Zeit im Kalender händisch gewartet bis der Bot mich in Telegram gespammed hat, dass er nicht buchen konnte, schnell den Monat im Kalender geswitched um einen Refresh zu triggern und konnte einen buchen. Hat 5 Anläufe gebraucht da die davor in 2 Sekunden weg waren 👍
